### ISSUE TITLE
Issue with previewing large files with figures

### ISSUE THREAD

**Issue by alsaibie** [ethan-ou/vscode-gift-preview#6]
Hi Ethan, 

I faced an issue when trying to preview a gift question that has multiple svg figures embedded. I did test it on Moodle and it displays fine. Is there a size limitation issue in the gift-preview extension, or is this something vscode related?

Attached is the file I'm trying to view for reference. 
[rlocus_written.gift.txt](https://github.com/ethan-ou/vscode-gift-preview/files/5249429/rlocus_written.gift.txt)

Thanks again, 

- Ali

**Comment by ethan-ou** [comment]
It looks like the issue is with line 1590 with your file. There's a couple of lines that injects CSS into the document:

```html
 <defs>
   <style type\="text/css">*\{stroke-linecap\:butt;stroke-linejoin\:round;\}</style>
 </defs>
```

Removing it brings back your graphs.

![Code_eOtgqDuOj4](https://user-images.githubusercontent.com/45083970/93692766-705c6600-fb3a-11ea-8473-dd860bd2454c.png)
![Code_wPmgNrYaXs](https://user-images.githubusercontent.com/45083970/93692767-718d9300-fb3a-11ea-9c1d-a45ca78d0ede.png)


This plugin doesn't actually do anything to your HTML except strip out leading `<p>` tags, so I'm not actually sure whether I can solve your issue.

**Comment by alsaibie** [comment]
Good catch. Perhaps because it redefines the style in the same question? As it works fine if I include a single plot, not two. Or have a plot per question with multiple questions on a page. I'll try to parse away this style injection on my end.

**Comment by ethan-ou** [comment]
It's pretty odd. I'm not sure if I could give a good explanation even if I tried. However, if you run into the same problem again, you can try using the VSCode Webview Developer Tools to look at the HTML that's being generated. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> then search for ` VSCode Webview Developer Tools` and see what's happening with any missing elements.

**Comment by alsaibie** [comment]
Thanks for the tip. 

The CSS style was introduced by the rlocus plot legend, it has a fancy setting, disabling it solved the issue.
